Chore/page no index
decidim-ice/decidim-anti-spam pull request #12
Opened 2023-08-28 16:33 UTC by rsdeus

I have had to create an initializer to configuring the app rails to user the gem

2023-08-28 22:51 UTC, froger requested changes
Hi,
You should take example on this module to implement deface: https://github.com/PopulateTools/decidim-module-extra_user_fields

See: 
- https://github.com/PopulateTools/decidim-module-extra_user_fields/blob/master/decidim-extra_user_fields.gemspec
- https://github.com/PopulateTools/decidim-module-extra_user_fields/blob/master/lib/decidim/extra_user_fields/engine.rb#L6
- https://github.com/PopulateTools/decidim-module-extra_user_fields/tree/master/app/overrides/decidim

2023-08-28 22:51 UTC, froger commented on config/initializers/deface.rb
> +# frozen_string_literal: true
No need to have this file, let the main rails app handle deface. 
Deface is also present in extra_user_fields and bunch of other decidim gems.

2023-08-28 22:51 UTC, froger commented on Gemfile
> +gem "deface", '~> 1.8', '>= 1.8.1'
Follow your gemspec here
```suggestion
gem "deface", '>= 1.8.1'
```

2023-08-29 09:48 UTC, rsdeus commented
Hi, all good now. Thanks for the help :heart:

2023-08-30 11:45 UTC, froger commented on Gemfile
> +gem "deface", '~> 1.8', '>= 1.8.1'
Hi @rsdeus I see no change here ;)

2023-08-30 12:58 UTC, froger approved these changes

2023-08-30 12:59 UTC, merged